### ISSUE TITLE
Boot Entry Protocol meta-issue

### ISSUE THREAD

**Issue by mikebeaton** [acidanthera/bugtracker#1777]
The following changes and updates are planned for the new Boot Entry Protocol after 0.7.3 release (note, are not required for correct operation of [OpenLinuxBoot](https://github.com/acidanthera/bugtracker/issues/1776) driver):

 - [x] In order to allow entry protocol drivers to provide own audio-assist, update OC sound protocol to work from string rather than int sound ids - https://github.com/acidanthera/OpenCorePkg/pull/346
 - [x] Upgrade boot entry protocol to support system actions - https://github.com/acidanthera/OpenCorePkg/pull/347
 - [x] Redo existing system actions (Reset NVRAM, Toggle SIP) as entry protocol drivers - https://github.com/acidanthera/OpenCorePkg/pull/347

**Comment by telepati** [comment]
Hi @mikebeaton. I don't understand anything about this new NVRAM setup. I read the whole guide I still didn't understand it. I am using the HideAuxilary, and when I click the OPT button and Enter, I can easily see the NVRAM reset tool. But now I can't see anything. 
In addition, what is that mean;
Supported optional Apple firmware-native NVRAM reset, thx @syncretic

Is it means that the boot entry will work the same as the previous version? 

Overall, As I understand, there is no built-in NVRAM reset set up in the new version OC. The ResetNvramEntry.efi driver must be active and what then! Please help me with how to set this up.

**Comment by mikebeaton** [comment]
Have you tried adding it as a driver? That is all you have to do, to get back the previous behaviour. It must be `Enabled=true`, ofc, like any other driver. It is not OPT or Enter to show auxiliary, it is SPACE.

**Comment by telepati** [comment]
@mikebeaton Of course, it is SPACE. Sorry, I just made a mistake while I writing. Thank you, now everything works.
