### ISSUE TITLE
Legacy OpenCore TODO

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#317]
This is a legacy TODO exported from requests, internal tracking, and other places in somewhat human readable format. We should migrate this to bugtracker and properly explain and/or fix. Development team only.

Feel free to create proper bugreports on each of these entries (and/or work on them) so they can be tracked separately and implemented more quickly.

- [x] Add booter patch support, moved to #380
- [x] OpenCoreUefi: OsInfo protocol is missing, moved to #383
- [x] OpenCore: loading via bcfg makes systems unbootable for obvious reasons (we should leave a config option once it works), ref: signal ReadyToBoot, moved to #382
- [x] OcWatermarkLib: Embed multiple versions (git hashes, dirty status, local commits) of all involved repositories, moved to #384
- [x] OcSmbiosLib: Add support for custom memory configuration, moved to #381
- [x] Add hibernation support (ref: https://github.com/al3xtjames/Clover/blob/9d6c0894ff8a97d225e1296e2a83f009b80feea9/rEFIt_UEFI/Platform/Hibernate.c#L1042)
- [x] Add secure boot support, moved to #368
- [x] OcBootManagementLib: Old dmg signatures, like mavericks, are not accepted due to untrusted certificate, we want to implement full LoadPolicy support, moved to #368
- [x] OcAppleImageVerificationLib: review & fix, it should be able to properly truncate the image when it has garbage in the end (consider ExtractVerifiedAppleImage interface with mutable Image/Size interface), moved to #368
- [x] OcDirectImageLoadLib: implement based off CoreImage files we already use in AppleImageLoader (see below); export OcDirectLoadImage, OcDirectStartImage, OcDirectUnloadImage as EFI gBS equivalents, moved to #368
- [x] OcAppleImageSupportLib: implements EFI_BOOT_SERVICES hook to its own functions, which implements Apple signature verification and FAT image loading (still need that for 10.8). Apple images should be loaded directly, moved to #368
- [x] OcAppleKernelLib: Add builtin XCPM patches for Ivy Bridge and other unsupported CPUs, moved to #365 
(https://applelife.ru/threads/razrabotka-opencore.2943955/page-14#post-800607)
- [x] OcAppleKernelLib: Add 10.13+ kernel panic verbose output patches as builtin
- [x] OcAppleKernelLib: Add builtin CPU ID patches, moved to #352
- [x] Library reference https://github.com/acidanthera/OcSupportPkg/blob/master/STATUS.md
- [x] OcConfigurationLib: Implement Tool section
- [x] <s>Logging: Log comments for kexts, acpi patches, and kext patches</s> Not beneficial, third party patches may be considered.
- [x] OcSmbiosLib: provide SMC information
- [x] OcSmbiosLib: <s>Legacy computers have SMBIOS changes invisible in Windows</s>, bugs in AIDA64
- [x] OpenCorePlatform: Allow to spoof bios vendor to Acidanthera (https://applelife.ru/threads/posts/804237)
- [x] <s>OcFirmwarePasswordLib: broken</s>, it is not like we can make a use of it right now.
- [x] OcConsoleLib: ConOut replace \t with space on ConOut → WriteString hook, as it breaks screen output on select firmwares, moved to #364
- [x] OpenCoreShell: In editor Ctrl + E does not work SimpleTextInputEx2ProtocolGuid… Try implementing UDK Hunk SimpleTextInput2 over SimpleTextInput? Explore it?, moved to #364
- [x] OcCpuLib: VMware core count is wrong, reports 2 instead of 4, moved to #363
- [x] OcCpuLib: Package count is always wrong, moved to #363
- [x] OcSerializeLib: Make invalid config keys cause fatal error
- [x] Docs: Consider adding to docs if it gets some love and exe/macOS bundle https://github.com/corpnewt/ProperTree??
- [x] Docs: Add warning about nvram garbage collection not working in many laptops to docs @ savvas
- [x] <s>OpenCore: Linux errors with SMC error on boot, try to report upstream in the first place</s>, does not reproduce
- [x] OcBootManagementLib: scan policy should really be two: no external devices (usb protocol, media external flag) and no filesystems but apfs, both enabled by default
- [x] <s>OcBootManagementLib: fix boot-image variable, it is in apple format</s>, I think it is unused, report otherwise
- [x] Docs: Add ACPI boot-args: acpi_level=0xFFFF5F, https://github.com/acpica/acpica/blob/master/source/include/acoutput.h#L185, ACPI_ALL_COMPONENTS, acpi_layer=0xFFFFFFFF
- [x] OpenCoreShell: load/drivers cause errors on older macs, moved to #364

**Comment by Andrey1970AppleLife** [comment]
Set **Displayed : 0** in **BGTR** for bios-logo as boot-logo Windows.
FIXME

**Comment by vit9696** [comment]
> Set Displayed : 0 in BGTR for bios-logo as boot-logo Windows.
Done in https://github.com/acidanthera/OpenCorePkg/commit/ef4cc2610df1978fb07a1e783b4ea2d80b53da9f

**Comment by PMheart** [comment]
Undone TODOs are now migrated to dedicated ones for better thoughts.
