### ISSUE TITLE
2019.10 release planning

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#486]
We want a relatively small bugfix release in October as new macOS is arriving shortly and it is not a good idea to break stuff right away.

- [x] OpenCore 0.5.1
    - [x] Add arguments to custom entries #468
    - [x] Merge AppleGenericInput into UEFI → Input section (#473)
    - [ ] Implement RUNTIME_DEBUG support ([reference](https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2689452))
    - [ ] Improve AvoidHighAlloc #449
    - [ ] Possibly other input improvements https://github.com/acidanthera/bugtracker/issues/485
    - [ ] Update the documentation ([reference](https://github.com/acidanthera/bugtracker/issues/486#issuecomment-535422976))
- [x] VoodooPS2 2.0.4
- [ ] VoodooPS2 2.1.0 (potentially)
   - [ ] Merge with VoodooInput interface #329
- [x] MacInfoPkg 2.0.8
- [ ] <s>BrcmPatchRAM 2.5.0</s>
- [x] VirtualSMC 1.0.8
- [x] WhateverGreen 1.3.3
- [x] AppleALC 1.4.2
- [x] AppleSupportPkg 2.1.1
- [x] HibernationFixup 1.2.9
@corpnewt, @kylon, @notiflux, since we are getting close to beta, September-October will be about the time for user apps to be in shape #330.

**Comment by Sniki** [comment]
It would be also nice to potentially include first release of Acidanthera/BrcmPatchRAM as it will be the Catalina release time and thousands of people will be affected with non-working Bluetooth.

Im glad you guys took over this project.

Respect for all of you.

**Comment by vit9696** [comment]
@Sniki, yeah, though it is mostly a formality, as we have not finished the migration yet. Recently we had a talk with @headkaze, and thought that it would be reasonable to work on this kext altogether on Acidanthera basis.

**Comment by vit9696** [comment]
I want these fixed by the release:

- [ ] https://github.com/acidanthera/bugtracker/issues/481
- [ ] https://github.com/acidanthera/bugtracker/issues/492
- [ ] https://github.com/acidanthera/bugtracker/issues/494
- [ ] https://github.com/acidanthera/bugtracker/issues/476
- [ ] https://github.com/acidanthera/bugtracker/issues/424

**Comment by Download-Fritz** [comment]
Rquired OpenCore documentation updates:
* The 'Troubleshooting' section does not recommend to load OpenCore.efi from Shell to reliably see its output. BOOTx64 does intentionally not switch to text mode on launch, which might hide important errors and give the impression of a crash.
* USB is mentioned twice at https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.tex#L2266

**Comment by DuIslingr** [comment]
@Download-Fritz that first thing is interesting because in QEMU I was not able to boot the OpenCore.efi directly. I had to use BOOTx64 to boot opencore. It said the OpenCore.efi was not an application when I tried.

**Comment by Download-Fritz** [comment]
@Dulslingr That is because OpenCore is not an application, it's a driver loaded with the "load" command.

**Comment by DuIslingr** [comment]
Oh ok that makes sense.

**Comment by vit9696** [comment]
So, current blockers are
- [ ] https://github.com/acidanthera/BrcmPatchRAM (fixing build and creating archives)
- [ ] https://github.com/acidanthera/bugtracker/issues/501 testing whether the fix worked
Afterwards we can release.

**Comment by balthild** [comment]
Before the release of acidanthera/BrcmPatchRAM, can I use RehabMan/OS-X-BrcmPatchRAM with OpenCore?
