### ISSUE TITLE
OpenCanopy meta issue

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#759]
This issue will cover all the current issues or basically feature requests from OpenCanopy. I will split this in three lists to make things easier for us:

- Undecided (what we know about but are unsure whether to implement or not)
- Accepted (what we plan to implement or already implemented)
- Rejected (what we decided not to implement or implement differently)

**Undecided**:
- [x] Boot timeout
- [x] dmg inscriptions
- [x] Per-os icons
- [x] Different icons for Windows (see [apple](https://support.apple.com/HT202796#startupmanager) original design draft) 
- [x] Different icons for TimeMachine
- [x] Different icons for Tools
- [x] White icon for external drives (see [apple](https://support.apple.com/HT202796#startupmanager) original design draft), *up to the user*
- [ ] Larger spacing, closer to [apple](https://support.apple.com/HT202796#startupmanager) original design draft rather than their actual implementation
- [x] `0` hotkey support (escape alias)
- [x] Password input support [PasswordIcon.zip](https://github.com/acidanthera/bugtracker/files/6152520/PasswordIcon.zip)
- [x] BackgroundColor (UserInterfaceTheme) is ignored, I believe we want to support grey at least. This will require dark grey inscriptions.
- [x] Scaling or scrolling animation when many icons are available
- [x] Label scrolling when it is longer than the maximum allowed width
- [ ] Seamless device hotplug support (may want to land in default picker first)
- [ ] Seamless device removal support (may want to land in default picker first)
- [ ] Device removal animation
- [ ] Device addition animation
- [x] Mouse movement may need adjusting for HiDPI mode
- [x] Custom icon support (`.VolumeIcon.icns`) in the volume root
- [x] Custom disk label support in image format)
- [ ] Support for hover/mouse-down images
- [x] 'hitbox' determination (e.g. rectangle, every pixel that is inbetween two non-transparent pixels, ...)
- [x] Additional mouse acceleration factor
- [x] Background image that would scale or centre
- [x] Add PickerVariant for icns
- [x] Add Restart and Shut Down icns. 
[BtnFocus_Var1.zip](https://github.com/acidanthera/bugtracker/files/6165069/BtnFocus_Var1.zip)
[BtnFocus_Var2.zip](https://github.com/acidanthera/bugtracker/files/6165070/BtnFocus_Var2.zip)
- [x] Dedicated set default icon for ctrl+enter [SetDefault.zip](https://github.com/acidanthera/bugtracker/files/6137060/SetDefault.zip)

**Accepted**:
- [x] Voice assistant support
- [x] AppleKeyMapAggregator hotkey handling
- [x] `PollAppleHotkeys`
- [x] `CMD+F5` hotkey (voice assistant toggle)
- [x] UI is not erased before entering UEFI Shell
- [x] HiDPI mode (UIScale = 2)
- [x] Missing Ext* icons must fall back to ExtHardDrive instead of an internal variant. Missing ExtHardDrive must cause an error-exit.
- [x] Error prints should be prohibited categorically to not stall boot. Instead, a warning should be printed and an error code should be returned from the protocol interface so that OC can fall back to the internal picker.
- [x] Esc conflicts with intro animation (#853)

**Rejected**:
- Wi-Fi user interface (we do not have reliable networking stack)
- Numeric hotkeys to choose the boot entry (we do not have place to write numbers)
- external inscriptions (we use icons for these)
- Add Clock (requires manual timezone specification, and more specifically it makes the UI a lot more cluttered)
- Text colour detection based on background image (there is no easy way to analyse the background image)

I uploaded the relevant media files and recordings [here](https://mega.nz/#!ykxRWQ5K!DhkxlaW3Nq0-6ial2AMeWRxu_AKF207NDQ_MyOZavrQ)  (encrypted with the standard password) and [here](https://github.com/acidanthera/bugtracker/files/4309059/media2.zip).

CC @usr-sse2 @Download-Fritz @Andrey1970AppleLife

**Comment by telepati** [comment]
I am an end-user and I have no information about the code. I can't do anything but admire you. I tested BootLiquor. I am using my computer like real mac behavior. Using the Opt key for reaching ShowPicker and clicking the SpaceBar for hiding Entries. I tested with Default Scan Policy and Scan Policy 0. 

I checked the link you share above. Text and PickerArrow look nice but with BootLiquor Text and PickerArrow very close to each other. I think these are must be fixed. If it is possible of course. I said earlier I don't know anything about programming or code.

![IMG_0382](https://user-images.githubusercontent.com/3812286/76165483-6d82c080-6168-11ea-9cca-b45289c15257.JPG)

I changed settings to Scan Policy 0 and put my Installer USB for testing how external drive shows. And it shows extra EFI driver I don't know what that is. It can be my Installer USB EFI maybe something else. Maybe this EFI can be hidden. Or maybe this is totally normal behavior of the OpenCore. I just let you know.

![IMG_0379](https://user-images.githubusercontent.com/3812286/76165651-bb4bf880-6169-11ea-9123-7e288f5e74dc.JPG)

Another problem is the Mouse Cursor. When pressing the Opt key and reach the ShowPicker Mouse Cursor sitting on the TopLeft of the screen and activating after 15 sec. And it's really moving very slow. Actually smoothing of the Mouse Cursor is really great but moving it's not. Definitely something wrong with the Mouse behavior. 

If posting this message here is wrong, please warn me to delete it. Thank you.

**Comment by Download-Fritz** [comment]
@telepati 
spacing: Apple spacing is pretty tight too, but it will probably be changed anyway
EFI: If HideSelf=false, it's probably OpenCore and if not, well, we do not know your setup. You can find out the associated boot file path from the OC log (Debug->Target)
cursor: This currently depends on the host firmware, some cause very slow mouse movements, yes. Probably there will be an option for a constant acceleration factor in the future.

**Comment by telepati** [comment]
@Download-Fritz 
Thank you. Yes, exactly you said HideSelf is set No on my config. I will change it and test it again. 

I test it ScanPolicy 0 without External Drive this time Time Machine disk shows up. 

Why is the Time Machine drive not visible when the External drive is inserted?

![IMG_0383](https://user-images.githubusercontent.com/3812286/76167064-ee47b980-6174-11ea-869f-cd3145d9658f.JPG)

**Comment by vit9696** [comment]
@telepati, for support requests better go to the forums. I do not want this issue to be polluted. The list of visible options should not change depending on the picker in the first place. Do be aware though that each picker depends on the OpenCore version and must be updated synchronously.

**Comment by telepati** [comment]
> @telepati, for support requests better go to the forums. I do not want this issue to be polluted. The list of visible options should not change depending on the picker in the first place. Do be aware though that each picker depends on the OpenCore version and must be updated synchronously.

The second post deleted. If the first post also unrelated please let me know I can delete it too.

**Comment by sspilleman** [comment]
Where can I find the password to extract the media files?

**Comment by vit9696** [comment]
It is team-only.

**Comment by asava** [comment]
Hi,

While debugging a problem with mouse support, I figured there is a mistake at InputSimAbsPtr.c:
[here](https://github.com/acidanthera/OpenCorePkg/blob/9eecf43c76b6cdcb72d4138a14375c0b5afbf276/Platform/OpenCanopy/Input/InputSimAbsPtr.c#L340) and [here](https://github.com/acidanthera/OpenCorePkg/blob/9eecf43c76b6cdcb72d4138a14375c0b5afbf276/Platform/OpenCanopy/Input/InputSimAbsPtr.c#L345): it should be "gST->ConsoleInHandle," instead of "&gST->ConsoleInHandle,".
I didn't want to open a new issue for this so I'm writing here.

**Comment by Download-Fritz** [comment]
@asava oh God, that's what you get for defining things as VOID *... tyvm, will fix

**Comment by najdanovicivan** [comment]
Timeout feature will be very useful especially in dual boot scenarios where default system will be able to boot automatically still allowing user to pick other system to boot

**Comment by telepati** [comment]
Will it be possible to adjust mouse movement and double click speed?

**Comment by romancin** [comment]
> Boot Timeout feature will be very useful especially in dual boot scenarios where default system will be able to boot automatically still allowing user to pick other system to boot

Totally agree. Without this, I am reverting back to Builtin. If I reboot my machine remotely, I would lost access to it because it would stuck on boot menu... 

Hope Boot Timeout is accepted any time soon :)

**Comment by mhaeuser** [comment]
Hey @Andrey1970AppleLife, could you please provide VoiceOver files for focus changes to shutdown and restart? For changing back to picker/password, we can use the existing intro messages imo.

**Comment by Andrey1970AppleLife** [comment]
> Hey @Andrey1970AppleLife, could you please provide VoiceOver files for focus changes to shutdown and restart? For changing back to picker/password, we can use the existing intro messages imo.

Hello! Yes I will make today.

**Comment by Andrey1970AppleLife** [comment]
@mhaeuser
Done 
[Restart_Shutdown.zip](https://github.com/acidanthera/bugtracker/files/6216388/Restart_Shutdown.zip)

**Comment by vit9696** [comment]
All planned features are implemented. Closing this.
